// Mocks generated by Mockito 5.3.2 from annotations
// in core/test/presentation/pages/tvseries/tvseries_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:core/core.dart' as _i9;
import 'package:core/domain/entities/tvseries.dart' as _i10;
import 'package:core/domain/entities/tvseries_detail.dart' as _i7;
import 'package:core/domain/usecases/tvseries/get_tvseries_detail.dart' as _i2;
import 'package:core/domain/usecases/tvseries/get_tvseries_recommendations.dart'
    as _i3;
import 'package:core/domain/usecases/tvseries/get_warchlist_status_tvseries.dart'
    as _i4;
import 'package:core/domain/usecases/tvseries/remove_watchlist_tvseries.dart'
    as _i6;
import 'package:core/domain/usecases/tvseries/save_watchlist_tvseries.dart'
    as _i5;
import 'package:core/presentation/provider/tvseries/tvseries_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvseriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvseriesDetail {
  _FakeGetTvseriesDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvseriesRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTvseriesRecommendations {
  _FakeGetTvseriesRecommendations_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchListStatusTvseries_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatusTvseries {
  _FakeGetWatchListStatusTvseries_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTvseries_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistTvseries {
  _FakeSaveWatchlistTvseries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTvseries_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistTvseries {
  _FakeRemoveWatchlistTvseries_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvseriesDetail_5 extends _i1.SmartFake
    implements _i7.TvseriesDetail {
  _FakeTvseriesDetail_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvseriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesDetailNotifier extends _i1.Mock
    implements _i8.TvseriesDetailNotifier {
  MockTvseriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvseriesDetail get getTvseriesDetail => (super.noSuchMethod(
        Invocation.getter(#getTvseriesDetail),
        returnValue: _FakeGetTvseriesDetail_0(
          this,
          Invocation.getter(#getTvseriesDetail),
        ),
      ) as _i2.GetTvseriesDetail);
  @override
  _i3.GetTvseriesRecommendations get getTvseriesRecommendations =>
      (super.noSuchMethod(
        Invocation.getter(#getTvseriesRecommendations),
        returnValue: _FakeGetTvseriesRecommendations_1(
          this,
          Invocation.getter(#getTvseriesRecommendations),
        ),
      ) as _i3.GetTvseriesRecommendations);
  @override
  _i4.GetWatchListStatusTvseries get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchListStatusTvseries_2(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i4.GetWatchListStatusTvseries);
  @override
  _i5.SaveWatchlistTvseries get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistTvseries_3(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i5.SaveWatchlistTvseries);
  @override
  _i6.RemoveWatchlistTvseries get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistTvseries_4(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i6.RemoveWatchlistTvseries);
  @override
  _i7.TvseriesDetail get tvseries => (super.noSuchMethod(
        Invocation.getter(#tvseries),
        returnValue: _FakeTvseriesDetail_5(
          this,
          Invocation.getter(#tvseries),
        ),
      ) as _i7.TvseriesDetail);
  @override
  _i9.RequestState get tvseriesState => (super.noSuchMethod(
        Invocation.getter(#tvseriesState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  List<_i10.TvSeries> get tvseriesRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvseriesRecommendations),
        returnValue: <_i10.TvSeries>[],
      ) as List<_i10.TvSeries>);
  @override
  _i9.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i9.RequestState.Empty,
      ) as _i9.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);
  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i11.Future<void> fetchTvseriesDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvseriesDetail,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tvseries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TvseriesDetail? tvseries) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tvseries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
