// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQvxFnNHnXtjKADZspl86-PYs_yGgY8Q',
    appId: '1:290675313369:web:8bc0e6cd8a32d95c1dccc8',
    messagingSenderId: '290675313369',
    projectId: 'ditonton-45ce6',
    authDomain: 'ditonton-45ce6.firebaseapp.com',
    storageBucket: 'ditonton-45ce6.appspot.com',
    measurementId: 'G-JNM4Y855WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77g7STfGnQwFxkmIKWRUom4gKqUIsaBY',
    appId: '1:290675313369:android:4e3cc695c225999b1dccc8',
    messagingSenderId: '290675313369',
    projectId: 'ditonton-45ce6',
    storageBucket: 'ditonton-45ce6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8SqpfN35y7eEQp28j9Q9A9xUdVmKUTI',
    appId: '1:290675313369:ios:15427ae4d31a37421dccc8',
    messagingSenderId: '290675313369',
    projectId: 'ditonton-45ce6',
    storageBucket: 'ditonton-45ce6.appspot.com',
    iosClientId: '290675313369-3nohqhmj8js6idrtqgcjc5d8hcros46v.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
